### ISSUE TITLE
Documentation on the SCSS compilation

### ISSUE THREAD

**Issue by DarkWizarD24** [megastruktur/foundryvtt-blades-in-the-dark#106]
Is it possible to provide an example on how to update the css ?

**Comment by megastruktur** [comment]
Hey @DarkWizarD24 ,
sure this is pretty easy: you can use the "sass" utility: https://www.npmjs.com/package/sass
Then just make all necessary changes inside scss files (style.scss) and after that execute something like this in scss dir:
`sass style.scss ../styles/blades.css`
So that css file is created. And commit both css and scss changes.
